### ISSUE TITLE
Не запускается main.py

### ISSUE THREAD

**Issue by seekerk** [Monsets/Eva#2]
После успешной установки приложение не запускается

kulakov@ultrabook:~/projects/Eva$ python3 ./main.py 
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from Application.mini_app import MiniApp
  File "/home/kulakov/projects/Eva/Application/mini_app.py", line 7, in <module>
    from pocketsphinx import LiveSpeech
ModuleNotFoundError: No module named 'pocketsphinx'

**Comment by seekerk** [comment]
Версия питона:

kulakov@ultrabook:~/projects/Eva$ python3 --version
Python 3.6.7
